// JavaScript Arrays: Review
// It's time to review! These examples are all taken from lessons that you've finished. Revisiting them makes sure that you haven't forgotten anything.
// Type in what each expression will evaluate to. For example, for the prompt 1 + 1, you would type 2.

const abc = [100, 200, 300];
abc.indexOf(300);

// RESULT:
// 2

// LESSON:
// Index of

const abc2 = [true, true, true];
abc2.indexOf(false);
// RESULT:
// -1