//JavaScript Arrays: Review
//It's time to review! These examples are all taken from lessons that you've finished.
//Revisiting them makes sure that you haven't forgotten anything.

//Type in what each expression will evaluate to. For example, for the prompt 1 + 1, you would type 2.

const strings = ['a', 'b', 'c'];
strings[0] = 'x';
strings;
RESULT:
['x', 'b', 'c']

// LESSON:
// Basics
// PROGRESS:
// Not confident?

['a', 'b', 'c'][0];
RESULT:
'a'

// LESSON:
// Basics
// PROGRESS:
// Not confident?