// JavaScript Arrays: Review
// It's time to review! These examples are all taken from lessons that you've finished. Revisiting them makes sure that you haven't forgotten anything.
// Type in what each expression will evaluate to. For example, for the prompt 1 + 1, you would type 2.

['Cindy', 'Dalili'].join();

// RESULT:
// 'Cindy,Dalili'

// LESSON:
// Join

const nums = [10, 20, 30];
nums.map(num => num * 10);
nums[1];

// RESULT:
// 20

// LESSON:
// Map

['first', undefined, null, 'last'].join();

// RESULT:
// 'first,,,last'

// LESSON:
// Join

[1, 2, 3].map(num => num * 100);

// RESULT:
// [100, 200, 300]

// LESSON:
// Map

['d', 'e', 'f'].join('_');

// RESULT:
// 'd_e_f'